name: Deploy to PyPi

on:
    push:
        branches: [ "main" ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.11"]
        permissions:
            contents: read
            id-token: write
        environment:
            name: pypi
            url: https://pypi.org/p/dsti_mlops_labs_egjfour
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install --upgrade build
                  python3 -m pip install --upgrade twine
            - name: Build
              run: |
                  python3 -m build
                  python3 -m twine upload --repository pypi dist/*
                  
      